server:
  port: 8080
spring:
  application:
    name: config-main
  data:
    mongodb:
      host: localhost
      port: 27017
      database: coderhouse-ecommerce
  app-auth:
    app:
      jwt:
        secret: keepSecretSafeOk98herfg9werhfn9p034h90werbgnw9p84erbtn9p3w48h9tj0rsfdgrtbdfghretrtyerdfgdfgertertertsdf
        expiration: 10000