server:
  port: 8080
spring:
  application:
    name: config-main
  datasource:
    url: mongodb://localhost:27017/coderhouse-ecommerce?createDatabaseIfNotExist=true
    username: root
    password: 60679194