server:
  port: 8080
spring:
  application:
    name: config-main
  datasource:
    url: jdbc:mysql://localhost:3306/coderhouse-ecommerce
    username: root
    password: 60679194
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  jpa-hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect